### ISSUE TITLE
As an admin, I need to add a tool to the app store

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/learn.duke#150]
- [ ] name
- [ ] description
- [ ] metadata (user limit, category, features, search keywords)
- [ ] logo and alt text
- [ ] tool's website and support site

**Comment by profmikegreene** [comment]
Duplicate of #89
