### ISSUE TITLE
Design research: outline desired look, feel, tone of design

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/learn.duke#167]
- [x] Create and send survey. Give it a week deadline?
- [x] Review and tabulate results 
- [x] Research and generate deliverable (tbd) to demonstrate and define desired direction for project
- [x] Finish refining design direction chosen
- [x] demo to larger team for feedback
- [x] demo to stakeholders for feedback

**Comment by bap13** [comment]
@curiousmustard let's figure out a date when you will be ready with the design edits/complete enough for us to demo to internal team and stakeholders.
@swwalker can you let me know who the stakeholders are that should be shown? Matthew, Evan, Shawn - anyone else?

**Comment by swwalker** [comment]
@bap13 - is this complete?

**Comment by bap13** [comment]
Yes, complete!
