### ISSUE TITLE
User feedback planning and execution: Manage Membership

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/learn.duke#177]
Plan and prepare for gathering end user feedback on manage membership feature
- [x] MG query all summer teaching faculty and email them an invite
- [ ] Schedule blocks of time for 6/11 - 6/15
- [ ] LH write script

**Comment by swwalker** [comment]
Can we close this issue?
