### ISSUE TITLE
Document existing provisioning flow for toolkits apps

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/learn.duke#206]
- [ ] #196 Sakai
- [ ] #170 Piazza
- [ ] Sites@Duke (WordPress)
- [ ] Box
- [ ] Duke Capture (Panopto)
- [ ] Duke Stream (Warpwire)
- [ ] Email list (Sympa)
- [ ] VCM
- [ ] VoiceThread
- [ ] Playposit
- [ ] #174 Qualtrics  
- [ ] Add a custom URL

**Comment by profmikegreene** [comment]
Moved to #198
